name: "2 - Build Transaction Backend"
on:
  push:
          branches: [main]   
    

jobs:
    build:
        
        runs-on: ubuntu-latest
        env:
          DOCKER_REPOSITORY: richiebono
          IMAGE_NAME: k8s-test
          IMAGE_TAG: ${{github.run_number}} # ${{ github.sha }}
          WORKING_DIRECTORY: .
          CLUSTER_NAME: k8s-test
          CLUSTER_REGION: us-east-1
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        defaults:
          run:
            shell: bash
            working-directory: ${{ env.WORKING_DIRECTORY }}

        steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
      
        - name: Terraform Init
          id: init
          run: terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -backend-config="region=${{ env.CLUSTER_REGION }}" 
        
        - name: Terraform Plan
          id: plan
          run: terraform plan -no-color -input=false
          continue-on-error: true

        - name: Terraform Plan Status
          if: steps.plan.outcome == 'failure'
          run: exit 1

        - name: Terraform Apply
          run: terraform apply -auto-approve -input=false

        - name: QEMU
          uses: docker/setup-qemu-action@v1

        - name: Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ env.DOCKER_REPOSITORY }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Build Docker Image ${{ env.IMAGE_NAME }}
          run: docker build -t ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -t ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest .
          
        - name: Push Docker Image ${{ env.IMAGE_NAME }}
          run: docker push ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}
        
        - name: Run Trivy Vulnerability Scanner
          uses: aquasecurity/trivy-action@master
          continue-on-error: true
          with:
            image-ref: 'docker.io/${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'MEDIUM,HIGH,CRITICAL'

        - name: Install kubectl
          uses: azure/setup-kubectl@v1
          with:
            version: 'v1.21.3'
          id: install

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.CLUSTER_REGION }}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Update kube config
          run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }}

        - name: Deploy image to Amazon EKS
          run: |           
            kubectl apply -f ../k8s/${{ env.WORKING_DIRECTORY }}/deployment.yaml
            kubectl apply -f ../k8s/${{ env.WORKING_DIRECTORY }}/service.yaml 

        - name: List kube nodes
          run: kubectl get svc