apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver3
  template:
    metadata:
      labels:
        app: webserver3
    spec:
      containers:
      - name: webserver3
        image: richiebono/k8s-test3
        ports:
        - containerPort: 8083
