name: "3 - Check Cluster"
on:
  workflow_dispatch:  

jobs:
    build:       
        runs-on: ubuntu-latest
        env:
          DOCKER_REPOSITORY: richiebono
          IMAGE_NAME: k8s-test
          IMAGE_TAG: ${{github.run_number}}
          WORKING_DIRECTORY: .
          CLUSTER_NAME: bono-k8s-test
          CLUSTER_REGION: us-east-1

        defaults:
          run:
            shell: bash
            working-directory: ${{ env.WORKING_DIRECTORY }}

        steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: QEMU
          uses: docker/setup-qemu-action@v1
        
        - name: Install kubectl
          uses: azure/setup-kubectl@v1
          with:
            version: 'v1.21.3'
          id: install

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.CLUSTER_REGION }}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Update kube config
          run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }}

        - name: List kube pods
          run: kubectl get pods 

        - name: List kube deployments
          run: kubectl get deployments

        - name: List kube services
          run: kubectl get svc

        