name: "4 - Destroy Infra"
on:
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
          DOCKER_REPOSITORY: richiebono
          IMAGE_NAME: k8s-test
          IMAGE_TAG: ${{github.run_number}}
          WORKING_DIRECTORY: .
          CLUSTER_NAME: bono-k8s-test
          CLUSTER_REGION: us-east-1

        defaults:
          run:
            shell: bash
            working-directory: ${{ env.WORKING_DIRECTORY }}

        steps:
          - name: Checkout Code
            uses: actions/checkout@v2

          - name: Install Terraform
            uses: hashicorp/setup-terraform@v1
            with:
                terraform_version: ${{ env.TERRAFORM_VERSION }}

          - name: Terraform Init
            id: init           
            run: terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -backend-config="region=${{ env.CLUSTER_REGION }}" 

          - name: Terraform Plan
            id: plan            
            run: terraform plan -no-color 

          - name: Terraform Apply Destroy       
            id: destroy  
            run: terraform destroy -auto-approve